[package]
name = "totally-not-malware"
version = "0.1.0"
authors = ["fawn <fawn@envs.net>"]
edition = "2021"
repository = "https://github.com/fawni/totally-not-malware"
license = "ISC"

[dependencies]
iced = { version = "0.7", features = ["image"] }

[profile.release]
panic = "abort"
lto = true
strip = true
codegen-units = 1
